### ISSUE TITLE
Occasional incorrect event on button 11 may be hardware in nature.

### ISSUE THREAD

**Issue by stefanoborini** [pimoroni/keybow-firmware#29]
I have a keybow that started to behave erratically with button 11. I am not an efficient lua programmer so initially I thought the problem was in the code. After a while I realised I could replicate the behavior by pressing the buttons harder or simply touching the keybow on the side, or slightly pulling the USB cable.

I did some investigation and, I might be wrong, but it seems that the black metallic pylon with the nut is short circuiting the contacts of key 11 right and key 8 left. The nut is not a zero ohm connection but it does conduct, especially when mechanically pressed.

Am I the only one experiencing these problems?

**Comment by stefanoborini** [comment]
On the topic, I just noticed that the instructions talk about plastic nuts, but I have metal ones.

**Comment by stefanoborini** [comment]
I fixed the problem by replacing the metal nut with a plastic ring from the core tube of a pen. 

![20190529_203717](https://user-images.githubusercontent.com/132967/58586126-49e22f80-8252-11e9-8bdb-e56d61676098.jpg)

**Comment by dglaude** [comment]
I believe this place is for code related issues. Pimoroni forum or support might be more appropriate. Maybe this could be closed now?
Thanks for the tip anyway.

**Comment by stefanoborini** [comment]
@dglaude It can be closed, and I agree with you. I opened it for anyone that may think they have a software problem with button 11 and start searching for clues.
