### ISSUE TITLE
pattern file called Tropical.png not a PNG file

### ISSUE THREAD

**Issue by retrorich75** [pimoroni/keybow-firmware#31]
The file called Tropical.png is not a PNG file but a Photoshop 8BPS file, maybe reload an exported png file ?

![Capture](https://user-images.githubusercontent.com/6966118/58862509-1586cd00-86b1-11e9-98a2-7edb3d76bfc7.PNG)

**Comment by Gadgetoid** [comment]
So it is, good spot! I've no idea how that happened, but I've fixed it. Thanks.
