### ISSUE TITLE
Document PNG to LED mapping. See #38

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/keybow-firmware#39]
The blog post linked in https://github.com/pimoroni/keybow-firmware/pull/38 makes a good point that our documentation lacks any explanation for how the pixels in PNG animations map to the LEDs on the keybow. We should fix this.

**Comment by b099l3** [comment]
Hey I took a shot at trying to improve the documentation for the PNG to LED mapping in this [blog post](https://iainsmith.me/keybow-lights/)

Is there a place for the documentation?

I created these images to help understand the mapping
![Web 1920 – 2](https://user-images.githubusercontent.com/877327/107087909-119b3e80-67f4-11eb-99e0-995c0fbc718d.png)
![Web 1920 – 5](https://user-images.githubusercontent.com/877327/107087914-12cc6b80-67f4-11eb-90b9-3c23ddf6a1dd.png)

**Comment by Extra-Fox** [comment]
Undocumented features are such a drag and while I really appreciate folks willing to take the time and energy to explore this, I'd be even more grateful for complete documentation from the OEM. I don't think it's enough to assume the "community" will help fill in the blanks.
