### ISSUE TITLE
KeybowNG - C++ compatible re-implementation

### ISSUE THREAD

**Issue by GothAck** [pimoroni/keybow-firmware#45]
I've been hacking on a re-implementation of the keybow code base, cleaning up some of the inter-dependencies, and hopefully making it easier to maintain and extend, would be interested in having a discussion with folks at Pimoroni about whether this is a good fit for future development of the keybow application & firmware. My code is up at https://github.com/GothAck/keybow-firmware/tree/keybowng. Things that still need to be implemented: serial and file access. Things I'm working on adding: Bluetooth HID support so keybow can easily be used with at least Android phones, hopefully other bluetooth devices as well :)

**Comment by Gadgetoid** [comment]
You've got my attention! I'll see if I can find the time to look over it sometime this week. I think I even managed to pack a Keybow or two before I fled the office to hide at home.
