### ISSUE TITLE
Keybow mouse support

### ISSUE THREAD

**Issue by gregprosser** [pimoroni/keybow-firmware#48]
Admittedly this project is called **key**bow, but would anyone be opposed if I put up a PR with mouse support of movement and buttons?

I needed it for a use case so I hacked it into the USB HID announcement and underlying code, and I have it working locally.

Currently it supports right/left/middle mouse clicks (and holds), and movement in pixels.

**Comment by mew-cx** [comment]
@gregprosser I'd welcome it.  IMO **key**bow is the name of the device that has keys, not the events sent from the device.

**Comment by Gadgetoid** [comment]
Mouse is merged, and it's awesome! Thank you all.
