### ISSUE TITLE
not able to access the bios with keybow 12

### ISSUE THREAD

**Issue by azcaban** [pimoroni/keybow-firmware#54]
I would like to use it during the boot, to access the bios, and other pre-OS options, but I did not find the way to let it work.
I noticed that as soon the password is asked to login in the OS, the 12-key keybow works, but not before, during the boot..
any idea to solve?

**Comment by Gadgetoid** [comment]
I don't think this is fixable- or at least I don't know where to start. Keybow isn't intended to function as a boot-compatible keyboard and I fear it might take quite a bit of effort to get it working as such.
