### ISSUE TITLE
Booting a keybow in USB device mode (ie: no sd card)

### ISSUE THREAD

**Issue by axelsimon** [pimoroni/keybow-firmware#55]
Hi,
KeybowOS is designed to run entirely in RAM in order to reduce SD card wear down.
With this in mind, it would make sense to be able to use the Raspberry Pi Zero's [USB device boot mode](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/device.md), in order to skip the SD card entirely:
> When this boot mode is activated (usually after a failure to boot from the SD card), the Raspberry Pi puts its USB port into device mode and awaits a USB reset from the host. Example code showing how the host needs to talk to the Pi can be found [here](https://github.com/raspberrypi/usbboot).

ie : plug Keybow to computer with no SD card, Keybow goes into device mode, computer sends KeybowOS/firmware, Keybow boots and appears as USB device (keyboard).
One could even automate sending KeybowOS from the computer.

I had a look, there are some references to the SD card in the RAM FS used in KeybowOS:
the `init` in the `initrd` creates `/dev/mmcblk0p1` and then mounts it on `/boot`.
I'm pretty new at this, so is this a way to pretend there is an SD card with `mknod` and then using it? Or does this depend on the actual SD card being there to work?

Further reading of Pimoroni's [rpi-ramdisk](https://github.com/pimoroni/rpi-ramdisk/tree/keybow#usb-device-boot) documentation, used to build KeybowOS, would make me think that a/ `mknod` is indeed used to create a partition for raspbian to be happy with, even though there is no actual underlying SD card and b/ that it should really not be too hard to use a Keybow with no SD card.

Having more info on how `keybow-firmware` is built (cf. #42 ) would be helpful here.

Lastly, for what it's worth, i did try to start the Keybow by booting it with `rpiboot -d keybow-0.0.4`. The files are sent and the Keybow appears to boot, but it's never picked up as a USB device by my laptop:
```terminal
sudo ./rpiboot -d ../Keybow/keybow-0.0.4/
Waiting for BCM2835/6/7/2711...
Sending bootcode.bin
Successful read 4 bytes 
Waiting for BCM2835/6/7/2711...
Second stage boot server
File read: config.txt
File read: start_cd.elf
File read: fixup_cd.dat
File read: config.txt
File read: config.txt
File read: cmdline.txt
File read: kernel.img
File read: initrd
File read: bcm2708-rpi-0-w.dtb
File read: config.txt
File read: overlays/dwc2.dtbo
Second stage boot server done
```

Thanks!

**Comment by Gadgetoid** [comment]
Keybow itself is actually run entirely out of /boot, the RAM disk image is *just* a cut down version of Raspbian with a startup script to run the keybow binary.

To be precise- the actual `keybow` executable is copied from `/boot` into the RAM disk by init before it's executed by the systemd unit. This is to allow easy software updates without having to rebuild and replace the entire initrd image.

init:

```
#!/bin/sh

sleep 0.2

mknod /dev/mmcblk0p1 b 179 1
mount -o rw /dev/mmcblk0p1 /boot

if [ -f "/boot/keybow" ]; then
        cp /boot/keybow /usr/bin/keybow
        chmod +x /usr/bin/keybow
        systemctl restart keybow
fi

exec /sbin/init
```

`etc/systemd/system/keybow.service`:

```
[Unit]
Description=Keybow Python Daemon
After=usb-gadget.service

[Service]
ExecStart=/usr/bin/keybow
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
```

The check for `/boot/keybow` in init might suggest that it fails over to a `usr/bin/keybow` inside the RAM disk image where the SD card is not available, but this (for better or worse) is not the case. Since Keybow relies upon the lua files and looks for them in `/boot` it'd probably fail even if it were in the RAM disk by default.

**Comment by axelsimon** [comment]
Hi @Gadgetoid, i really appreciate you answering and providing context.

Having now booted the Keybow from an SD card, i can infirm what i was saying previously: the Keybow never finishes booting when started in USB device mode and providing it a target directory from which to boot with `sudo ./rpiboot -d ../Keybow/keybow-0.0.4/`

Happy to try to tinker some more with this with a bit of guidance, but otherwise i don't think the original request has really been answered.
