### ISSUE TITLE
USB Descriptors

### ISSUE THREAD

**Issue by billybicep** [pimoroni/keybow-firmware#65]
Hi, Is it possible to change the USB desciptors on the keybow mini?

Specifically I've told i need to ' change the USB descriptors to report a BOOTMODE keyboard that uses a standard 8-byte report.' in order for it to work on the hardware i have.

**Comment by Gadgetoid** [comment]
In theory yes, you can edit - https://github.com/pimoroni/keybow-firmware/blob/master/keybow/gadget-hid.c

In practise... USB HID descriptors are an eldritch horror and modifying them will no-doubt have knock-on effects on how the rest of the code works. This is not something I have the bandwidth to look into at the moment.
