### ISSUE TITLE
Media Keys template nonfunctional on macOS and Linux

### ISSUE THREAD

**Issue by ab-gh** [pimoroni/keybow-firmware#66]
Made a fresh install of Keybow OS on a Keybow (non-mini), switched keys.lua to the media keys template.

macOS saw the input device, and the keybow successfully booted up and lit LEDs correctly, but no buttons would work.

Same thing with Linux, on openSUSE Tumbleweed KDE

**Comment by lyndell** [comment]
Same, though it works on my other Mac.  🤔

**Comment by lyndell** [comment]
> Same, though it works on my other Mac. 🤔

I made the mistake of using a USB cable with a switch; meaning it's a power only USB cable.  Switch to a data USB cable, the  blink layout works; blinking and typing numbers in TextEdit.  Switch to the _mini_playback.lua_, layout works as expected.  Tested in YouTube and Music.
