### ISSUE TITLE
True Lights FPS?

### ISSUE THREAD

**Issue by dglaude** [pimoroni/keybow-firmware#7]
The learning guide ( https://learn.pimoroni.com/tutorial/sandyj/setting-up-the-keybow-os ) say: "The animations are displayed at 30fps."

The code (and comment) in file keybow/keybow.c say 60 in function void *run_lights(void *void_ptr){

**Comment by sandyjmacdonald** [comment]
Thanks, David. You're quite right. I was getting confused with the Picade Plasma button frame rate, which we dialled down to 30fps, IIRC. I've corrected the tutorial.
