### ISSUE TITLE
Official Keybow schematics?

### ISSUE THREAD

**Issue by mew-cx** [pimoroni/keybow-firmware#71]
Be handy to have official schematics for Keybow.
To include LED numbering, key GPIO assignments, etc.

**Comment by eXsoR65** [comment]
@mew-cx The Keybow HAT is owned by Pimoroni, so don't expect to get a schematics. 

If you are looking to see the order of leds you can can use [this](https://iainsmith.me/keybow-lights/) to guide you

**Comment by mew-cx** [comment]
Hmm, didn't realize Pimoroni was known to keep such info private.  It's easy to rev-eng this info, just thought the official source would be more definitive.

Thanks for the pointer to that guide.

Since I created this over a year ago, I'll close.
