### ISSUE TITLE
Booting Issue First Time (doesn't boot & no lights)

### ISSUE THREAD

**Issue by Sanchez8868** [pimoroni/keybow-firmware#73]
I flashed the custom KeyBow OS on a 32 GB SanDisk Extreme micro SD card, I have tried two different ones. This card works for every other OS I have tried except this one. When Connected to a monitor the rainbow screen appears and that's all.

**Comment by Gadgetoid** [comment]
What Pi were you attempting to boot Keybow OS on? Since it's missing "kernel7" it only works on a Pi Zero/Pi Zero W and older Pi's based on the same BCM chips.
