### ISSUE TITLE
Makefile/script instructions to rebuild initrd/initramfs?

### ISSUE THREAD

**Issue by gregkh** [pimoroni/keybow-firmware#74]
The Makefile works great for building the application, but how was the initrd/initramfs created?

Any hint on the script/command used to rebuild it so that we can debug / modify things easier?

thanks!

**Comment by Gadgetoid** [comment]
It's built using `rpi-ramdisk` from this branch on our fork - https://github.com/pimoroni/rpi-ramdisk/tree/keybow

Bit of a non-trivial, non-standard mess that I haven't had the opportunity to clean up and automate yet.

**Comment by gregkh** [comment]
I didn't notice that repo, thanks, will look into it!

**Comment by gregkh** [comment]
And many thanks for the quick response, and the software / keyboard, it's a lot of fun.
