### ISSUE TITLE
macros running twice

### ISSUE THREAD

**Issue by GalacticSerialBus** [pimoroni/keybow-firmware#75]
When I use macros or snippets that use `set_modifier()`, the macro will run twice. It seems to be running once when I press the button down then again once the button is released. this doesn't happen when I use the set key modifier by itself.

**Comment by Gadgetoid** [comment]
Do you have some example code? All of the key handlers are called on press/release so you usually need to check the state and do the right thing.

**Comment by jolo1581** [comment]
@GalacticSerialBus 
When I tried first, I got the same problem.

I solved it with:

```
function handle_minikey_01(pressed)
    if pressed then
        -- add code to execute on key press here 
    else
        -- do nothing on release
     end
end
```

Greetz
Jan
