### ISSUE TITLE
bluetooth available?

### ISSUE THREAD

**Issue by panchovie** [pimoroni/keybow-firmware#76]
I'm using keybow mini on pi zero W/H. Is it possible to use bluetooth instead of the usb-mini line to connect to PCs.

**Comment by Gadgetoid** [comment]
Theoretically, I think so, but Bluetooth is a whole can of worms I don't have the time (or inclination... it's a potential horrorshow) to open.

**Comment by panchovie** [comment]
Thank you, I understand. Hope it will come, w/ enough firearms!
