### ISSUE TITLE
os.date

### ISSUE THREAD

**Issue by diilmac** [pimoroni/keybow-firmware#83]
trying to input date by pressing key, but im getting year 2016 somehow.
how to fix it?

keybow.text(os.date ("%Y-%m-%d"))

**Comment by Gadgetoid** [comment]
Keybow doesn't have a network connection, nor any way to store and maintain the current time. There are probably workarounds, but at best this would be unreliable and probably significantly more complicated than just using AutoHotKey or something on the host computer.
