### ISSUE TITLE
How to use GPIO with keybow

### ISSUE THREAD

**Issue by loudoweb** [pimoroni/keybow-firmware#85]
I'm having fun with the project but I don't see anything to play with GPIO in the current LUA api. How can I read and write GPIO?

Thanks.

**Comment by Gadgetoid** [comment]
That's very far outside the scope of this project, I'm afraid.

**Comment by cinderblockgames** [comment]
@loudoweb Were you able to get anything working?

**Comment by loudoweb** [comment]
> @loudoweb Were you able to get anything working?

It was a long time ago! I think you need to not use the lua api. Not sure if I really tried. Sorry.
