### ISSUE TITLE
Too many *.dtb files on sdcard if this is for PiZero only...

### ISSUE THREAD

**Issue by dglaude** [pimoroni/keybow-firmware#9]
The SD card contain the following dtb where maybe only those for PiZero (and 3A?) that support Gadget mode on USB are useful:

- bcm2708-rpi-0-w.dtb
- bcm2708-rpi-b-plus.dtb
- bcm2708-rpi-b.dtb
- bcm2708-rpi-cm.dtb
- bcm2709-rpi-2-b.dtb
- bcm2710-rpi-3-b-plus.dtb
- bcm2710-rpi-3-b.dtb
- bcm2710-rpi-cm3.dtb

A few bytes could be saved here.

**Comment by TheDiveO** [comment]
Maybe some users might want to debug on a Pi3* using the HDMI connector before switching back to the Pi0?

**Comment by dglaude** [comment]
For debugging purpose, I would compile the keybow binary and run that on a full fledge Raspbian.
You just need to compile keybow disabling the USB Gadget output, and maybe enabling debug code.
But the main use of keybow is if you have a Raspberry Pi with no USB hub and capable of being an USB gadget. This mean any PiZero, a Pi3A+ and maybe a modified "Raspberry Pi 1 Model A+".

Maybe unrelated, but the same microSD that works on a PiZero, does fail to boot my working "Raspberry Pi 3 Model A+" so either the kernel is too old, or it is missing a *.dtb file.

**Comment by TheDiveO** [comment]
Thank you for the information! At the moment I'm now using a mocked keybow version to run my basic tests on the development system. This catches syntax errors, etc. early and reduces the wearing rinse-and-repeat cycle quite good.

**Comment by sandyjmacdonald** [comment]
David: in my testing, this is the minimal set of .dtb files that are required to boot the OS, but if you can find a way to use fewer then great!

**Comment by ali1234** [comment]
Given that you can't buy an SD card smaller than 4GB any more there isn't really any reason to limit the installed dtbs and overlays. They don't use any memory if they aren't loaded.
